{% set version = '1.7.2' %}
{% set major_ver = version.split(".")[0] %}

package:
  name: dtc-package
  version: {{ version }}

source:
  url: https://git.kernel.org/pub/scm/utils/dtc/dtc.git/snapshot/dtc-{{ version }}.tar.gz
  sha256: 8f1486962f093f28a2f79f01c1fd82f144ef640ceabe555536d43362212ceb7c

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - bison
    - flex
    - meson
    - swig <4.2
    - pkg-config
  host:
    - python {{ python }}
    - setuptools
    - yaml
    - valgrind
  run:
    - python {{ python }}

outputs:
  - name: dtc
    files:
      include:
        - bin/*
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - meson
        - pkg-config
      host:
        - {{ pin_subpackage("libfdt", exact=True) }}
        - yaml
        - valgrind
      run:
        - {{ pin_subpackage("libfdt", max_pin="x.x") }}
    test:
      commands:
        - convert-dtsv0 --help
        - dtc --help
          # dtdiff is a shell script that can pipe two device-tree files through dtc and diff them
          # there are no specific tests for it in the dtc testsuite and the diff isn't completely
          # clean even if you run 'dtdiff tests/test_tree1.{dts,dtb}' because the representation
          # of various data is formatted slightly differently in the unpacked dtb
        - 'test -x "$PREFIX"/bin/dtdiff'
        - fdtdump --help
        - fdtget --help
        - fdtoverlay --help
        - fdtput --help
    about:
      summary: 'Linux Kernel Device Tree Compiler (dtc)'
      description: |
       Device Tree Compiler (dtc) toolchain for working with device
       tree source and binary files
      license: GPL-2.0-or-later
      license_family: GPL2
      license_file:
        - GPL
        - README.license
  - name: pylibfdt
    files:
      include:
        - lib/python*/site-packages/
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - meson
        - pkg-config
        - swig <4.2
      host:
        - {{ pin_subpackage("libfdt", exact=True) }}
        - python {{ python }}
        - setuptools
      run:
        - {{ pin_subpackage("libfdt", max_pin="x.x") }}
        - python {{ python }}
    test:
      imports:
        - libfdt
    about:
      summary: 'Python Bindings for Linux Kernel Device Tree library (libfdt)'
      description: |
        Python bindings for libfdt, a utility library for reading and manipulating the Linux Kernel
        Device Tree binary format.
      license: GPL-2.0-or-later OR BSD-2-Clause
      license_family: BSD
      license_file:
        - GPL
        - BSD-2-Clause
        - README.license
  - name: libfdt
    files:
      include:
        - include/
        - lib/
      exclude:
        - lib/python*/site-packages/
    build:
      run_exports:
        - {{ pin_subpackage("libfdt", max_pin="x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - meson
        - pkg-config
    test:
      commands:
        # tests/run_tests.sh -t libfdt depends on having dtc and the other binaries installed
        # we include those tests when packaging 'dtc' because it depends on having 'libfdt'
        - test -f $PREFIX/include/libfdt.h
        - test -f $PREFIX/include/fdt.h
        - test -f $PREFIX/include/libfdt_env.h
        - test -f $PREFIX/lib/libfdt.a
        - test -f $PREFIX/lib/libfdt${SHLIB_EXT}
        - test -f $PREFIX/lib/libfdt${SHLIB_EXT}.{{ major_ver }}
        - test -f $PREFIX/lib/libfdt${SHLIB_EXT}.{{ version }}
    about:
      summary: 'Linux Kernel Device Tree library (libfdt)'
      description: |
        libfdt, a utility library for reading and manipulating the Linux Kernel
        Device Tree binary format.
      license: GPL-2.0-or-later OR BSD-2-Clause
      license_family: BSD
      license_file:
        - GPL
        - BSD-2-Clause
        - README.license


about:
  home: https://git.kernel.org/pub/scm/utils/dtc/dtc.git
  summary: 'Toplevel for subpackages dtc, libfdt and pylibfdt'
  license: GPL-2.0-or-later
  license_family: GPL
  license_file:
    - GPL
    - README.license

extra:
  recipe-maintainers:
    - timsnyder
