schema_version: 1

context:
  version: "1.8.1"
  major_ver: "${{ (version | split('.'))[0] }}"
  python_min: "3.10"

recipe:
  name: dtc-package
  version: ${{ version }}

source:
  url: https://git.kernel.org/pub/scm/utils/dtc/dtc.git/snapshot/dtc-${{ version }}.tar.gz
  sha256: 74b50bb19134f6562490afea53e59953dd6c4afb17e5ccb60be32221262d3390

build:
  number: 0
  skip: win

outputs:
  - staging:
      name: dtc-build
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - bison
        - flex
        - pkg-config
        - meson
        - if: build_platform != target_platform
          then:
            - python ${{ python_min }}.*
            - cross-python_${{ target_platform }}
        - swig
      host:
        - python      ${{ python_min }}.*
        - python-abi3 ${{ python_min }}.*
        - setuptools
        - pip
        - yaml

  - package:
      name: dtc
    inherit: dtc-build
    build:
      files:
        - bin/convert-dtsv0
        - bin/dtc
        - bin/dtdiff
        - bin/fdtdump
        - bin/fdtget
        - bin/fdtoverlay
        - bin/fdtput
    requirements:
      run:
        - ${{ pin_subpackage("libfdt", upper_bound="x.x") }}
    tests:
      - script:
          - convert-dtsv0 --help
          - dtc --help
          - test -x "$PREFIX"/bin/dtdiff
          - fdtdump --help
          - fdtget --help
          - fdtoverlay --help
          - fdtput --help
    about:
      summary: Linux Kernel Device Tree Compiler (dtc)
      description: |
        Device Tree Compiler (dtc) toolchain for working with device
        tree source and binary files
      license: GPL-2.0-or-later
      license_file:
        - GPL
        - README.license

  - package:
      name: pylibfdt
    inherit: dtc-build
    build:
      files:
        - lib/python*/
      python:
        version_independent: true
    requirements:
      host:
        - ${{ pin_subpackage("libfdt", exact=True) }}
      run:
        - ${{ pin_subpackage("libfdt", upper_bound="x.x") }}
        - python >=${{ python_min }}
    tests:
      - python:
          imports:
            - libfdt
          pip_check: false
      - files:
          source:
            - if: build_platform == target_platform and linux
              then:
                - tests/
                - build/dtc
                - build/tests/test_tree1.dtb
                - build/tests/aliases.dtb
        script:
          - if: build_platform == target_platform and linux
            then:
              - cd build/tests && NO_PYTHON=0 ../../tests/run_tests.sh -t pylibfdt
    about:
      summary: Python Bindings for Linux Kernel Device Tree library (libfdt)
      description: |
        Python bindings for libfdt, a utility library for reading and manipulating the Linux Kernel
        Device Tree binary format.
      license: GPL-2.0-or-later OR BSD-2-Clause
      license_file:
        - GPL
        - BSD-2-Clause
        - README.license

  - package:
      name: libfdt
    inherit:
      from: dtc-build
      run_exports: false
    build:
      files:
        - include/*
        - lib/libfdt.*
        - lib/pkgconfig/libfdt.*
    requirements:
      run_exports:
        - ${{ pin_subpackage("libfdt", upper_bound="x.x") }}
    tests:
      - script:
          - test -f $PREFIX/include/libfdt.h
          - test -f $PREFIX/include/fdt.h
          - test -f $PREFIX/include/libfdt_env.h
          - test -f $PREFIX/lib/libfdt.a
          - test -f $PREFIX/lib/libfdt${SHLIB_EXT}
          - if: osx
            then:
              - test -f $PREFIX/lib/libfdt.${{ major_ver }}${SHLIB_EXT}
          - if: linux
            then:
              - test -f $PREFIX/lib/libfdt${SHLIB_EXT}.${{ major_ver }}
              - test -f $PREFIX/lib/libfdt${SHLIB_EXT}.${{ version }}
    about:
      summary: Linux Kernel Device Tree library (libfdt)
      description: |
        libfdt, a utility library for reading and manipulating the Linux Kernel
        Device Tree binary format.
      license: GPL-2.0-or-later OR BSD-2-Clause
      license_file:
        - GPL
        - BSD-2-Clause
        - README.license

about:
  summary: Toplevel for subpackages dtc, libfdt and pylibfdt
  license: GPL-2.0-or-later
  license_file:
    - GPL
    - README.license
  homepage: https://git.kernel.org/pub/scm/utils/dtc/dtc.git

extra:
  recipe-maintainers:
    - timsnyder
    - blmaier
  feedstock-name: dtc-package
